services:
  - type: web
    name: bsai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
